### ISSUE TITLE
FYI, CLI11 group now maintains official package

### ISSUE THREAD

**Issue by solvingj** [ess-dmsc/conan-cli11#2]
You may still have need to maintain your own package, but maybe not.  

https://bintray.com/cliutils/CLI11/CLI11%3Acliutils

In any case, thanks for all the OSS contributions!

**Comment by SkyToGround** [comment]
This package was created to bring in a feature that had not yet been merged with the master branch of CLI11. Seeing as that feature is now available in the master branch, this package is not as useful anymore. We have for this reason considered removing it and we probably will soon.
